name: Check if project compiles

on:
  push:
    branches:
      - "feature/*"
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build_linux:
    name: On Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build RType on Linux
        run: |
          sudo pip install conan
          conan profile new --detect default
          cmake -S . -B build
          cd build
          cmake --build .
  build_windows:
    name: On Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Build RType on Windows
        shell: pwsh
        run: |
          pip install conan
          cmake -S . -B build -G "Visual Studio 17 2022"
          cd build/
          cmake --build .
