name: Run tests

on:
  push:
    branches:
      - "feature/*"
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build OtterLib Tests
        run: |
          sudo pip install conan
          conan profile new --detect default
          cmake -S . -B build
          cd build
          cmake --build . --target OtterLibTests
      - name: Run OtterCore Tests
        if: always()
        run: |
          ./OtterLib/build/bin/OtterCoreTests
      - name: Run OtterNetwork Tests
        if: always()
        run: |
          ./OtterLib/build/bin/OtterNetworkTests
      - name: Run OtterGraphic Tests
        if: always()
        run: |
          ./OtterLib/build/bin/OtterGraphicTests