name: Run tests

on:
  push:
    branches:
      - "feature/*"
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build OtterLib Tests
        run: |
          cd OtterLib
          sudo pip install conan==1.57.0
          conan profile new --detect default
          cmake -S . -B build -DBUILD_TESTING=ON
          cmake --build build --target OtterLibTests
      - name: Run OtterCore Tests
        if: always()
        run: |
          ./build/bin/OtterCoreTests
      - name: Run OtterNetwork Tests
        if: always()
        run: |
          ./build/bin/OtterNetworkTests
      - name: Run OtterGraphic Tests
        if: always()
        run: |
          ./build/bin/OtterGraphicTests
      - name: Run OtterScripting Tests
        if: always()
        run: |
          ./build/bin/OtterScriptingTests
